### ISSUE TITLE
Keybind in Config not working

### ISSUE THREAD

**Issue by Tilltheprogamer** [BeansFL/E-Panicbutton#1]
I tryed to set a key for the panicbutton and i couldnt set any key not with the index number or the correct Default QWERTY frome the fivem guide.

**Comment by BeansFL** [comment]
Check FiveM Keybinds if set to true in config

**Comment by Tilltheprogamer** [comment]
Ist on true by default i pressed 0 nothing came

BeansFL ***@***.***> schrieb am Sa., 9. Sept. 2023, 01:19:

**Comment by BeansFL** [comment]
This is weird since it completely worked on my server and also servers of friends, try to check your keybinds.

**Comment by Tilltheprogamer** [comment]
Got no section for Thatcher in the keybinds

BeansFL ***@***.***> schrieb am So., 10. Sept. 2023, 10:36:

**Comment by BeansFL** [comment]
Wich means its set on false. I may take a look when im on my pc or try to dm me by following our discord link in the readme!
